width       = 800
height      = 600
zoomf       = 1.1
transflatef = 0.25
software    = 0
iter_step   = 10
speed_step  = 0.33
preset      = 0

[[presets]]
generator = "mandelbrot"
center    = { x = -0.7, y = 0.0 }
dpp       = 0.0035
max_iter  = 50

[[presets]]
generator = "julia"
center    = { x = 0.0, y = 0.0 }
dpp       = 0.00425
max_iter  = 50
julia     = { x = -0.8, y = 0.156 }

[[presets]]
generator = "julia"
center    = { x = 0.0, y = 0.0 }
dpp       = 0.00425
max_iter  = 50
julia     = { x = -0.4, y = 0.6 }

[[presets]]
generator = "julia"
center    = { x = 0.0, y = 0.0 }
dpp       = 0.00425
max_iter  = 50
julia     = { x = 0.285, y = 0.01 }

[[presets]]
generator = "julia_multiset"
dynamic   = true
speed     = 1.0
center    = { x = 0.0, y = 0.0 }
dpp       = 0.00425
max_iter  = 50
julia     = { x = 0.7885, y = 0.7885 }
n         = 2
